spring:
  #   base de datos posta
  datasource:
    url: jdbc:mysql://localhost/politics
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create-drop

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: admin
      password: admin
    realmImportFile: politics-realm.json



