spring:
  #   base de datos posta
  datasource:
    url: jdbc:mysql://localhost/politics
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: admin
      password: admin
    realmImportFile: politics-realm.json

server:
  port: 8083


