server:
  port: 8091
spring:
  #   base de datos posta
  datasource:
    url: jdbc:postgresql://localhost:3307/politics
    username: root
    password: password

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update

  batch:
    job:
      enabled: false
    initialize-schema: ALWAYS

file:
  input: zonas.csv

